package db2project.entity;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "manswer", schema = "DB2Project")
public class MAnswer implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//Unique id generated by the persistence provider
    private int id;

    @ManyToOne
    @JoinColumn(name = "review")
    private Review review;

    @ManyToOne
    @JoinColumn(name = "question")
    private MQuestion question;

    private String text;

    public MAnswer() { }

    public MAnswer(Review review, MQuestion question, String text) { //Update both sides of the relationships
        this.review = review;
        this.question = question;
        this.text = text;
        review.addAnswer(this);
        question.addAnswer(this);
    }

    public int getId() { return id; }
    //public void setId(int id) { this.id = id; }

    public Review getReview() { return review; }
    //public void setReview(Review review) { this.review = review; }

    public MQuestion getQuestion() { return question; }
    //public void setQuestion(MQuestion question) { this.question = question; }

    public String getText() {
        return text;
    }
    //public void setText(String text) { this.text = text; }

}
