package db2project.entity;

import javax.persistence.*;
import java.util.LinkedList;
import java.util.List;

@Entity
@Table(name = "MQuestion", schema = "DB2Project")
public class MQuestion {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//Unique id generated by the persistence provider
    private int id;

    @ManyToOne
    @JoinColumn(name = "product")
    private Product product;

    private String text;

    @OneToMany(
        fetch = FetchType.EAGER,
        mappedBy = "question",
        cascade = { CascadeType.PERSIST, CascadeType.REMOVE, CascadeType.REFRESH },
        orphanRemoval = true
        // quando viene effettuata l'operazione X su di me (MQuestion), effettuala anche a questa relazione (MAnswer)
    )
    private List<MAnswer> answers;

    public void addAnswer(MAnswer a) {
        if (answers == null) {
            answers = new LinkedList<>();
        }
        answers.add(a);
    }


    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public Product getProduct() { return product; }
    public void setProduct(Product product) { this.product = product; }

    public String getText() { return text; }
    public void setText(String text) { this.text = text; }




    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MQuestion mQuestion = (MQuestion) o;
        return id == mQuestion.id;
    }

    @Override
    public int hashCode() { return id; }
}
