package db2project.entity;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "offensive_words", schema = "DB2Project")
@NamedQuery(name = "OffensiveWords.getAll", query = "SELECT w FROM OffensiveWords w")
public class OffensiveWords implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//Unique id generated by the persistence provider
    private String word;

    public OffensiveWords() { }

    public String getWord() {
        return word;
    }
    //public void setWord(String word) { this.word = word; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OffensiveWords that = (OffensiveWords) o;
        return that.word.equals(this.word);
    }

    @Override
    public int hashCode() {
        return word != null ? word.hashCode() : 0;
    }
}
