package entity;

import javax.persistence.*;

@Entity
public class MAnswer {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//Unique id generated by the persistence provider
    private int id;

    @ManyToOne
    @JoinColumn(name = "review")
    private Review review;

    @ManyToOne
    @JoinColumn(name = "question")
    private MQuestion question;

    private String text;

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public Review getReview() { return review; }
    public void setReview(Review review) { this.review = review; }

    public MQuestion getQuestion() { return question; }
    public void setQuestion(MQuestion question) { this.question = question; }

    public String getText() {
        return text;
    }
    public void setText(String text) {
        this.text = text;
    }






    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MAnswer mAnswer = (MAnswer) o;
        return id == mAnswer.id;
    }

    @Override
    public int hashCode() {
        return id;
    }
}
